name: Context

on:
  pull_request:
    types: closed
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ toJSON(github) }}'
    - run: which go
    - uses: actions/setup-go@v5
      with:
        cache: false
    - run: which go
    - run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf $AGENT_TOOLSDIRECTORY
    - run: which go
