name: Context

on:
  pull_request:
    types: closed
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo $AGENT_TOOLSDIRECTORY
    - run: which go
    - run: ls -al /usr/bin/go
    - run: ls -al /opt/hostedtoolcache/go/1.21.7/x64/bin/go
    - run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf $AGENT_TOOLSDIRECTORY
    - run: which go
    - run: echo '${{ toJSON(github) }}'
