name: Context

on:
  pull_request:
    types: closed
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: which go
    - run: ls -al /usr/bin/go
    - run: ls -al /opt/hostedtoolcache/go/1.21.7/x64/bin/go
    - run: echo '${{ toJSON(github) }}'
