name: Dispatch Test
on:
  push:
    branches:
    - master
    - release/*
    paths:
    - test/**
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    working-directory: test

env:
  TARGET: ${{ (github.event_name == 'workflow_dispatch' && 'prod') || (startsWith(github.ref, 'refs/heads/release/') && 'stg') || (github.ref == 'refs/heads/master' && 'dev') }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo dispatch test
