name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove existing kustomize and install it again
        run: |
          sudo rm /usr/local/bin/kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - name: Installed Kustomize version
        run: ./kustomize version
      - run: ./kustomize build .
