name: Test

on:
  push:
    branches:
    - master
    - release/**

jobs:
  test:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: kustomize build .
